version: 0.2

phases:
  build:
    commands:
       - npm install
       - npm run build
      #  npm run test
      #  - npm run start
      # - npm run start:prod

# artifacts:
#   files:
#     - '**/*'